network:
  version: 2
  ethernets:
    ens33:
      dhcp4: false
      addresses: [10.0.0.30/24]
      routes:
          - to: 0.0.0.0/0
            via: 10.0.0.1
      nameservers:
          addresses: [10.0.0.10]
