network:
  version: 2
  ethernets:
    ens33:
      dhcp4: false
      addresses: [192.168.197.254/24]
      nameservers:
        addresses: [1.1.1.1, 8.8.8.8]
      routes:
        - to: 0.0.0.0/0
          via: 192.168.197.2
    ens34:
      dhcp4: false
      addresses: [10.0.0.1/24]